# Generated by Django 5.0.1 on 2024-01-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='CategoryName',
            new_name='categoryName',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='imgurl',
            new_name='imageurl',
        ),
    ]
