# Generated by Django 5.0.1 on 2024-01-18 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_categoryname_category_categoryname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='wathlisit',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
